services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-for-testing
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - infra-testing.env
    volumes:
      - neo4j_infra_volume:/var/lib/neo4j

  minio:
    image: minio/minio:latest
    container_name: minio-for-testing
    env_file:
      - infra-testing.env
    ports:
      - "9000:9000"    
      - "9001:9001"
    command: server /data --console-address ":9001"

volumes:
  neo4j_infra_volume:
 