title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!

base_url: /docs

just_the_docs:
  search_enabled: true
  navigation:
    - title: "Home"
      url: "/"
    - title: "Data Model"
      url: "/data-model"

collections:
  pages:
    output: true
  data-model:
    output: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
